import { Button, Stack, Typography } from '@mui/material';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { useContext, useState } from 'react';
import { LoginContext } from '../lib/LoginContext';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const context = useContext(LoginContext);

  const [aknowledge, setAknowledge] = useState(false);

  return (
    <div className={styles.container}>
      <Head>
        <title>Welcome to PolyCode !</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className={styles.title}>Welcome to PolyCode !</h1>

      <Typography variant="subtitle1" sx={{ textAlign: 'center' }}>
        The interview cracking platform
      </Typography>

      {!context.user && (
        <>
          {aknowledge ? (
            <div style={{ textAlign: 'center' }}>
              <Typography sx={{ marginTop: '5rem' }} variant="h6">
                To use the platform, you must have an account.
              </Typography>

              <Stack direction="row" spacing={2} sx={{
                marginTop: '3rem',
                justifyContent: 'center',
              }}>
                <Link href="/register" passHref>
                  <Button color="secondary" variant="contained">
                    I don’t have an account (register)
                  </Button>
                </Link>
                <Link href="/login" passHref>
                  <Button color="secondary" variant="contained">
                    I already have an account (log in)
                  </Button>
                </Link>
              </Stack>
            </div>
          ) : (
            <div style={{ textAlign: 'center' }}>
              <Typography sx={{ marginTop: '5rem' }} variant="h6">
                (Manifesto) Easy to use, powerful and powered by Polycode-Runner
                !
              </Typography>
              <Button
                size="large"
                variant="contained"
                color="secondary"
                onClick={() => setAknowledge(true)}
                sx={{ marginTop: '5rem' }}
              >
                Let’s go !
              </Button>
            </div>
          )}
        </>
      )}
    </div>
  );
};

export default Home;
